### ISSUE TITLE
Deploy to heroku using custom domain name

### ISSUE THREAD

**Issue by wildlySpeculating** [theTravelingCodesmen/goodbyeYall#13]

**Comment by scko823** [comment]
https://devcenter.heroku.com/articles/custom-domains
http://stackoverflow.com/questions/11492563/heroku-godaddy-send-naked-domain-to-www
http://stackoverflow.com/questions/7170664/how-to-configure-heroku-application-dns-to-godaddy-domain

some references. leaving it here so I can come back to it later. link 3 point to link 2 as an updated post

https://devcenter.heroku.com/articles/pointdns
there seems to be a heroku addon for it
