### ISSUE TITLE
Fork me on GitHub Ribbon

### ISSUE THREAD

**Issue by scko823** [theTravelingCodesmen/goodbyeYall#238]
I added a fork me on GitHub ribbon to the page, but having trouble with showing it correctly (css)
please clone down the fork-ribbon branch and fine tune the css

Here is the [github](https://github.com/simonwhitaker/github-fork-ribbon-css/) for the repo, and here is an [example page](https://simonwhitaker.github.io/github-fork-ribbon-css/)

The problem I have is that the two dotted lines in the ribbon, the ribbon is too small and it does not extend beyond the bottom dotted line.

**Comment by owentemple** [comment]
done
